book/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<book_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^(?P<book_id>[0-9]+)/comment/$', views.comment, name='comment'),
        url(r'^(?P<book_id>[0-9]+)/support/$', views.support, name='support'),
        ]

cookbook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<cookbook_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<cookbook_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^(?P<cookbook_id>[0-9]+)/comment/$', views.comment, name='comment'),
        url(r'^(?P<cookbook_id>[0-9]+)/support/$', views.support, name='support'),
        ]

pynxl/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pynxl.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('homepage.urls')),
    url(r'^foodmaterial/', include('foodmaterial.urls')),
    url(r'^cookbook/', include('cookbook.urls')),
    url(r'^movie/', include('movie.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^image/', include('image.urls')),
    url(r'^star/', include('star.urls')),
    url(r'^health/', include('health.urls')),
    url(r'^shopping/', include('shopping.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^usercenter/', include('usercenter.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^djadmin/', include('djadmin.urls')),
]

cookbook/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from datetime import datetime, timedelta

from django.db import models
from django.conf import settings

from django.utils import timezone
from django.utils.timesince import timesince

class CrawlerCookbookInfo(models.Model):
    id = models.IntegerField('美食编号')
    website = models.CharField('网站来源', max_length=255, blank=True)
    srcid = models.CharField('采集编号', primary_key=True, max_length=255, blank=True)
    srclink = models.CharField('采集URL', max_length=255, blank=True)
    type = models.IntegerField('一级分类', blank=True, null=True)
    extratype = models.IntegerField('二级分类', blank=True, null=True)
    name = models.CharField('美食名称', max_length=255, blank=True)
    comment = models.TextField('美食评论', blank=True)
    main_spice = models.TextField('美食主料', blank=True)
    assist_spice = models.TextField('美食辅料', blank=True)
    cooks = models.CharField('厨具', max_length=255, blank=True)
    classify = models.CharField('分类', max_length=255, blank=True)
    trick = models.TextField('小技巧', blank=True)
    viewnum = models.IntegerField('浏览', blank=True)
    supportnum = models.IntegerField('支持', blank=True)
    againstnum = models.IntegerField('反对', blank=True)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_cookbook_info'
        verbose_name = '美食信息'
        verbose_name_plural = '美食信息'

    def labels_as_list(self):
        return self.classify.split('\n')

    def get_time_string(self):
        timedelta = timesince(self.createtime).split(',')[0]
        if timedelta.find('minute') != -1:
            minutes = timedelta.split('\xa0')[0]
            if minutes <> '0':
                return minutes + '分钟前'
            else:
                return '刚刚'
        elif timedelta.find('hour') != -1:
            return timedelta.split('\xa0')[0] + '小时前'
        elif timedelta.find('day') != -1:
            return timedelta.split('\xa0')[0] + '天前'
        elif timedelta.find('month') != -1:
            return timedelta.split('\xa0')[0] + '个月前'
        elif timedelta.find('week') != -1:
            return timedelta.split('\xa0')[0] + '周前'
        elif timedelta.find('year') != -1:
            return timedelta.split('\xa0')[0] + '年前'
        else:
            return timedelta

class CrawlerCookbookStep(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerCookbookInfo', db_column='srcid', on_delete=models.CASCADE)
    imgid = models.CharField('图片ID', max_length=255)
    imglink = models.CharField('图片链接', max_length=255)
    imgpath = models.CharField('图片路径', max_length=255)
    step_method = models.TextField('步骤', blank=True)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_cookbook_step'
        verbose_name = '做菜方法'
        verbose_name_plural = '做菜方法'

class CrawlerCookbookImg(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerCookbookInfo', db_column='srcid', on_delete=models.CASCADE)
    imgid = models.CharField('图片ID', max_length=255)
    imglink = models.CharField('图片链接', max_length=255)
    imgpath = models.CharField('图片路径', max_length=255)
    imgtitle = models.TextField('标题', blank=True)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_cookbook_img'
        verbose_name = '美食图片'
        verbose_name_plural = '美食图片'

class CrawlerCookbookComment(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerCookbookInfo', db_column='srcid', on_delete=models.CASCADE)
    comment = models.TextField('评论内容', blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='用户')
    supportnum = models.IntegerField('支持', blank=True)
    createtime = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'crawler_cookbook_comment'
        verbose_name = '美食评论'
        verbose_name_plural = '美食评论'

cookbook/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import json
import urllib2

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaulttags import register

from django import template
from django.utils import timezone
from django.views.generic import View, TemplateView, ListView, DetailView

from homepage.models import Website, Column
from .models import CrawlerCookbookInfo, CrawlerCookbookStep, CrawlerCookbookImg, CrawlerCookbookComment

@register.filter(name='mod_lookup')
def mod_lookup(num, val):
    return num % val

def index(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=2)

    cookbook_list = CrawlerCookbookInfo.objects.order_by('-createtime')[:1000]
    hottest_list = CrawlerCookbookInfo.objects.order_by('-viewnum')[:10]

    paginator = Paginator(cookbook_list, 20)
    try:
        cookbooks = paginator.page(1)
    except EmptyPage:
        cookbooks = paginator.page(paginator.num_pages)

    page_range = list(paginator.page_range)[0:5]

    context = {'site_info': site_info, 
            'column_list': column_list,
            'column_now': column_now,
            'cookbook_list': cookbooks,
            'query_num': len(cookbook_list),
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'cookbook/index.html', context)

def search(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=2)

    cookbook_list = CrawlerCookbookInfo.objects.all()
    query = request.GET.get('q')
    if query and len(query):
        cookbook_list = cookbook_list.filter(name__contains=query.encode('utf-8'))

    tag = request.GET.get('tag')
    if tag and len(tag):
        cookbook_list = cookbook_list.filter(classify__contains=tag.encode('utf-8'))

    sort = request.GET.get('sort')
    if sort == '1':
    	cookbook_list = cookbook_list.order_by('-createtime')[:1000]
    elif sort == '2':
    	cookbook_list = cookbook_list.order_by('-viewnum')[:1000]
    elif sort == '3':
    	cookbook_list = cookbook_list.order_by('-supportnum')[:1000]
    else:
        sort = '1'
    	cookbook_list = cookbook_list.order_by('-createtime')[:1000]

    page = request.GET.get('page', 1)
    paginator = Paginator(cookbook_list, 20)
    try:
        cookbooks = paginator.page(page)
    except PageNotAnInteger:
        cookbooks = paginator.page(1)
    except EmptyPage:
        cookbooks = paginator.page(paginator.num_pages)

    page_num = int(page)
    if page_num >= 5:
        page_range = list(paginator.page_range)[page_num-5:page_num+4]
    else:
        page_range = list(paginator.page_range)[0:page_num+4]

    hottest_list = CrawlerCookbookInfo.objects.order_by('-viewnum')[:10]

    context = {'site_info': site_info, 
            'column_list': column_list, 
            'column_now': column_now,
            'query': query,
            'sort': int(sort),
            'query_num': len(cookbook_list),
            'cookbook_list': cookbooks,
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'cookbook/search.html', context)

def detail(request, cookbook_id):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=2)

    cookbook = get_object_or_404(CrawlerCookbookInfo, srcid=str(cookbook_id))
    cookbook.viewnum += 1
    cookbook.save()

    hottest_comment_list = []
    latest_comment_list = cookbook.crawlercookbookcomment_set.order_by('-createtime')
    if len(latest_comment_list) > 30:
        hottest_comment_list = cookbook.crawlercookbookcomment_set.order_by('-supportnum')[:5]

    hottest_list = CrawlerCookbookInfo.objects.order_by('-viewnum')[:10]

    context = {'site_info': site_info, 
            'column_list': column_list, 
            'column_now': column_now,
            'cookbook': cookbook,
            'hottest_comment_list': hottest_comment_list,
            'latest_comment_list': latest_comment_list,
            'hottest_list': hottest_list,}
    return render(request, 'cookbook/detail.html', context)

def vote(request, cookbook_id):
    article_type = request.POST.get("type")

    cookbook = get_object_or_404(CrawlerCookbookInfo, srcid=str(cookbook_id))

    response = {}
    response['status'] = 0

    if article_type == '1':
        cookbook.supportnum += 1
        cookbook.save()

        response['message'] = 'ok'
        response['supportnum'] = cookbook.supportnum
        response['againstnum'] = cookbook.againstnum
    elif article_type == '2':
        cookbook.againstnum += 1
        cookbook.save()

        response['message'] = 'ok'
        response['supportnum'] = cookbook.supportnum
        response['againstnum'] = cookbook.againstnum
    else:
        response['status'] = -1
        response['message'] = 'param type error!'

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

def comment(request, cookbook_id):
    comment = request.POST.get("comment")
    user = request.user

    if not user.is_authenticated():
        return HttpResponse("亲，你还没有登录哦！", status=403)

    if not comment:
        return HttpResponse("请输入评论内容！", status=403)

    if len(comment.strip())<5:
        return HttpResponse("评论内容内容过短！", status=403)

    cookbook_comment = CrawlerCookbookComment()
    cookbook_comment.srcid = CrawlerCookbookInfo.objects.get(srcid=str(cookbook_id))
    cookbook_comment.comment = comment
    cookbook_comment.user = user
    cookbook_comment.supportnum = 0
    cookbook_comment.againstnum = 0
    cookbook_comment.save()

    context = {'latest': cookbook_comment,}
    return render(request, "cookbook/latest_comment.html", context)

def support(request, cookbook_id):
    cid = request.POST.get("cid")

    comment = get_object_or_404(CrawlerCookbookComment, id=cid)

    response = {}
    response['status'] = 0

    comment.supportnum += 1
    comment.save()

    response['message'] = 'ok'
    response['supportnum'] = comment.supportnum

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

cookbook/templates/cookbook/index.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation"><a href="/cookbook/search/?q=&sort=3">推荐</a></li>
                        <li role="presentation"><a href="/cookbook/search/?q=&sort=2">热门</a></li>
                        <li role="presentation" class="active"><a href="/cookbook/search/?q=&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if cookbook_list %}
                    <ul class="list-group">
                        {% for cookbook in cookbook_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="{{ cookbook.crawlercookbookimg_set.first.imglink }}" alt="{{ cookbook.crawlercookbookimg_set.first.name }}" style="height: 100px; width: 150px" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/cookbook/{{ cookbook.srcid }}">
                                                    <strong>{{ cookbook.name|slice:"50" }}</strong>
                                                </a>
                                            </h4>
                                        </div>

                                        <div class="article-labels">
                                            {% for label in cookbook.labels_as_list %}
                                                <a href="/cookbook/search/?tag={{ label }}"><span class="label label-pynxl-{{ forloop.counter|mod_lookup:6 }}">{{ label }}</span></a>
                                            {% endfor %}
                                        </div>

                                        </br>

                                        <div class="atricle-content">
                                            <div>
                                                <p>{{ cookbook.comment|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                {{ cookbook.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-comment"></span>
                                                {{ cookbook.crawlercookbookcomment_set.count }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ cookbook.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if cookbook_list.has_previous %}
                            <a href="/cookbook/search/?q=&page={{ cookbook_list.previous_page_number }}&sort=1" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num cookbook_list.number %}
                            <li class="active">
                                <span class="current">{{ cookbook_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/cookbook/search/?q=&page={{ page_num }}&sort=1">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if cookbook_list.has_next %}
                            <a href="/cookbook/search/?q=&page={{ cookbook_list.next_page_number }}&sort=1" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门美食</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/cookbook/{{ hottest.srcid }}">{{ hottest.name }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

cookbook/templates/cookbook/search.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation" {% ifequal sort 3 %}class="active"{% endifequal %}><a href="/cookbook/search/?q={{ query }}&sort=3">推荐</a></li>
                        <li role="presentation" {% ifequal sort 2 %}class="active"{% endifequal %}><a href="/cookbook/search/?q={{ query }}&sort=2">热门</a></li>
                        <li role="presentation" {% ifequal sort 1 %}class="active"{% endifequal %}><a href="/cookbook/search/?q={{ query }}&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if cookbook_list %}
                    <ul class="list-group">
                        {% for cookbook in cookbook_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="{{ cookbook.crawlercookbookimg_set.first.imglink }}" alt="{{ cookbook.crawlercookbookimg_set.first.name }}" style="height: 100px; width: 150px" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/cookbook/{{ cookbook.srcid }}">
                                                    <strong>{{ cookbook.name|slice:"50" }}</strong>
                                                </a>
                                            </h4>
                                        </div>

                                        <div class="article-labels">
                                            {% for label in cookbook.labels_as_list %}
                                                <a href="/cookbook/search/?tag={{ label }}"><span class="label label-pynxl-{{ forloop.counter|mod_lookup:6 }}">{{ label }}</span></a>
                                            {% endfor %}
                                        </div>

                                        </br>

                                        <div class="atricle-content">
                                            <div>
                                                <p>{{ cookbook.comment|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                {{ cookbook.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-comment"></span>
                                                {{ cookbook.crawlercookbookcomment_set.count }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ cookbook.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if cookbook_list.has_previous %}
                            <a href="/cookbook/search/?q={{ query }}&page={{ cookbook_list.previous_page_number }}&sort={{ sort }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num cookbook_list.number %}
                            <li class="active">
                                <span class="current">{{ cookbook_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/cookbook/search/?q={{ query }}&page={{ page_num }}&sort={{ sort }}"">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if cookbook_list.has_next %}
                            <a href="/cookbook/search/?q={{ query }}&page={{ cookbook_list.next_page_number }}&sort={{ sort }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门美食</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/cookbook/{{ hottest.srcid }}">{{ hottest.name }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}