book/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<book_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^(?P<book_id>[0-9]+)/comment/$', views.comment, name='comment'),
        url(r'^(?P<book_id>[0-9]+)/support/$', views.support, name='support'),
        ]

pynxl/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pynxl.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('homepage.urls')),
    url(r'^foodmaterial/', include('foodmaterial.urls')),
    url(r'^cookbook/', include('cookbook.urls')),
    url(r'^movie/', include('movie.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^image/', include('image.urls')),
    url(r'^star/', include('star.urls')),
    url(r'^health/', include('health.urls')),
    url(r'^shopping/', include('shopping.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^usercenter/', include('usercenter.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^djadmin/', include('djadmin.urls')),
]

star/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<star_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<star_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^(?P<star_id>[0-9]+)/comment/$', views.comment, name='comment'),
        url(r'^(?P<star_id>[0-9]+)/support/$', views.support, name='support'),
        ]

star/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from datetime import datetime

from django.db import models
from django.conf import settings
from django.utils import timezone

class CrawlerStarInfo(models.Model):
    id = models.IntegerField('明星编号')
    website = models.CharField('网站来源', max_length=255, blank=True)
    srcid = models.CharField('采集编号', primary_key=True, max_length=255, blank=True)
    srclink = models.CharField('采集URL', max_length=255, blank=True)
    type = models.IntegerField('一级分类', blank=True, null=True)
    extratype = models.IntegerField('二级分类', blank=True, null=True)
    name = models.CharField('明星名', max_length=255, blank=True)
    engname = models.CharField('英文名', max_length=255, blank=True)
    aliase = models.CharField('别名', max_length=255, blank=True)
    gender = models.CharField('性别', max_length=255, blank=True)
    birthday = models.CharField('生日', max_length=255, blank=True)
    profession = models.CharField('职业', max_length=255, blank=True)
    area = models.CharField('地区', max_length=255, blank=True)
    company = models.CharField('经纪公司', max_length=255, blank=True)
    school = models.CharField('毕业学校', max_length=255, blank=True)
    intro = models.TextField('简介', blank=True)
    achievement = models.TextField('个人成就', blank=True)
    viewnum = models.IntegerField('浏览', blank=True)
    supportnum = models.IntegerField('支持', blank=True)
    againstnum = models.IntegerField('反对', blank=True)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_star_info'
        verbose_name = '明星信息'
        verbose_name_plural = '明星信息'

    def get_time_string(self):
        return self.createtime.strftime("%Y-%m-%d %H:%M:%S")

    def get_achievement(self):
        return self.achievement.split(';')

class CrawlerStarRelation(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerStarInfo', db_column='srcid', on_delete=models.CASCADE)
    relation_id = models.CharField('人物ID', max_length=255)
    relationship = models.CharField('关系', max_length=255)
    name = models.CharField('姓名', max_length=255)
    portraitpath = models.CharField('头像路径', max_length=255)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_star_relation'
        verbose_name = '明星关系'
        verbose_name_plural = '明星关系'

class CrawlerStarImg(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerStarInfo', db_column='srcid', on_delete=models.CASCADE)
    imgid = models.CharField('图片ID', max_length=255)
    imglink = models.CharField('图片链接', max_length=255)
    imgpath = models.CharField('图片路径', max_length=255)
    portraitid = models.CharField('头像ID', max_length=255)
    portraitlink = models.CharField('头像链接', max_length=255)
    portraitpath = models.CharField('头像路径', max_length=255)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_star_img'
        verbose_name = '明星图片'
        verbose_name_plural = '明星图片'

class CrawlerStarComment(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerStarInfo', db_column='srcid', on_delete=models.CASCADE)
    comment = models.TextField('评论内容', blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='用户')
    supportnum = models.IntegerField('支持', blank=True)
    createtime = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'crawler_book_comment'
        verbose_name = '电影评论'
        verbose_name_plural = '电影评论'

star/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import json
import urllib2

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaulttags import register

from django import template
from django.utils import timezone
from django.views.generic import View, TemplateView, ListView, DetailView

from homepage.models import Website, Column
from .models import CrawlerStarInfo, CrawlerStarRelation, CrawlerStarImg, CrawlerStarComment

@register.filter(name='mod_lookup')
def mod_lookup(num, val):
    return num % val

def index(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=7)

    star_list = CrawlerStarInfo.objects.order_by('-viewnum')[:1000]
    hottest_list = CrawlerStarInfo.objects.order_by('-supportnum')[:10]

    paginator = Paginator(star_list, 20)
    try:
        stars = paginator.page(1)
    except EmptyPage:
        stars = paginator.page(paginator.num_pages)

    page_range = list(paginator.page_range)[0:5]

    context = {'site_info': site_info, 
            'column_list': column_list,
            'column_now': column_now,
            'star_list': stars,
            'query_num': len(star_list),
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'star/index.html', context)

def search(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=7)

    star_list = CrawlerStarInfo.objects.all()
    query = request.GET.get('q')
    if query and len(query):
        star_list = star_list.filter(name__contains=query.encode('utf-8'))

    sort = request.GET.get('sort')
    if sort == '1':
    	star_list = star_list.order_by('-createtime')[:1000]
    elif sort == '2':
    	star_list = star_list.order_by('-viewnum')[:1000]
    elif sort == '3':
    	star_list = star_list.order_by('-supportnum')[:1000]
    else:
        sort = '1'
    	star_list = star_list.order_by('-createtime')[:1000]

    page = request.GET.get('page', 1)
    paginator = Paginator(star_list, 20)
    try:
        stars = paginator.page(page)
    except PageNotAnInteger:
        stars = paginator.page(1)
    except EmptyPage:
        stars = paginator.page(paginator.num_pages)

    page_num = int(page)
    if page_num >= 5:
        page_range = list(paginator.page_range)[page_num-5:page_num+4]
    else:
        page_range = list(paginator.page_range)[0:page_num+4]

    hottest_list = CrawlerStarInfo.objects.order_by('-supportnum')[:10]

    context = {'site_info': site_info,
            'column_list': column_list,
            'column_now': column_now,
            'query': query,
            'sort': int(sort),
            'query_num': len(star_list),
            'star_list': stars,
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'star/search.html', context)

def detail(request, star_id):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=7)

    star = get_object_or_404(CrawlerStarInfo, srcid=str(star_id))
    star.viewnum += 1
    star.save()

    hottest_comment_list = []
    latest_comment_list = star.crawlerstarcomment_set.order_by('-createtime')
    if len(latest_comment_list) > 30:
        hottest_comment_list = star.crawlerstarcomment_set.order_by('-supportnum')[:5]

    hottest_list = CrawlerStarInfo.objects.order_by('-supportnum')[:10]

    context = {'site_info': site_info, 
            'column_list': column_list, 
            'column_now': column_now,
            'star': star,
            'hottest_comment_list': hottest_comment_list,
            'latest_comment_list': latest_comment_list,
            'hottest_list': hottest_list,}
    return render(request, 'star/detail.html', context)

def vote(request, star_id):
    article_type = request.POST.get("type")

    star = get_object_or_404(CrawlerStarInfo, srcid=str(star_id))

    response = {}
    response['status'] = 0

    if article_type == '1':
        star.supportnum += 1
        star.save()

        response['message'] = 'ok'
        response['supportnum'] = star.supportnum
        response['againstnum'] = star.againstnum
    elif article_type == '2':
        star.againstnum += 1
        star.save()

        response['message'] = 'ok'
        response['supportnum'] = star.supportnum
        response['againstnum'] = star.againstnum
    else:
        response['status'] = -1
        response['message'] = 'param type error!'

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

def comment(request, star_id):
    comment = request.POST.get("comment")
    user = request.user

    if not user.is_authenticated():
        return HttpResponse("亲，你还没有登录哦！", status=403)

    if not comment:
        return HttpResponse("请输入评论内容！", status=403)

    if len(comment.strip())<5:
        return HttpResponse("评论内容内容过短！", status=403)

    star_comment = CrawlerStarComment()
    star_comment.srcid = CrawlerStarInfo.objects.get(srcid=str(star_id))
    star_comment.comment = comment
    star_comment.user = user
    star_comment.supportnum = 0
    star_comment.againstnum = 0
    star_comment.save()

    context = {'latest': star_comment,}
    return render(request, "star/latest_comment.html", context)

def support(request, star_id):
    cid = request.POST.get("cid")

    comment = get_object_or_404(CrawlerStarComment, id=cid)

    response = {}
    response['status'] = 0

    comment.supportnum += 1
    comment.save()

    response['message'] = 'ok'
    response['supportnum'] = comment.supportnum

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

star/templates/star/index.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation"><a href="/star/search/?q=&sort=3">推荐</a></li>
                        <li role="presentation" class="active"><a href="/star/search/?q=&sort=2">热门</a></li>
                        <li role="presentation"><a href="/star/search/?q=&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if star_list %}
                    <ul class="list-group">
                        {% for star in star_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="http://119.61.64.177/img001/{{ star.crawlerstarimg_set.first.imgpath }}" style="height: 200px; width: 132px" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/star/{{ star.srcid }}">
                                                    <strong>{{ star.name|slice:"50" }}</strong>
                                                    <small>{{ star.aliase }}</small>
                                                </a>
                                            </h4>
                                        </div>

                                        </br>

                                        <div class="article-content">
                                            <div>
                                                <p>{{ star.intro|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                <span class="glyphicon glyphicon-calendar"></span>
                                                {{ star.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ star.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if star_list.has_previous %}
                            <a href="/star/search/?q={{ query }}&page={{ star_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num star_list.number %}
                            <li class="active">
                                <span class="current">{{ star_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/star/search/?q={{ query }}&page={{ page_num }}"">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if star_list.has_next %}
                            <a href="/star/search/?q={{ query }}&page={{ star_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门明星</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/star/{{ hottest.srcid }}">{{ hottest.name }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

star/templates/star/search.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation" {% ifequal sort 3 %}class="active"{% endifequal %}><a href="/star/search/?q={{ query }}&sort=3">推荐</a></li>
                        <li role="presentation" {% ifequal sort 2 %}class="active"{% endifequal %}><a href="/star/search/?q={{ query }}&sort=2">热门</a></li>
                        <li role="presentation" {% ifequal sort 1 %}class="active"{% endifequal %}><a href="/star/search/?q={{ query }}&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if star_list %}
                    <ul class="list-group">
                        {% for star in star_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="http://119.61.64.177/img001/{{ star.crawlerstarimg_set.first.imgpath }}" style="height: 200px; width: 132px" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/star/{{ star.srcid }}">
                                                    <strong>{{ star.name|slice:"50" }}</strong>
                                                    <small>{{ star.get_release_time_string|slice:"4" }}</small>
                                                </a>
                                            </h4>
                                        </div>

                                        </br>

                                        <div class="atricle-content">
                                            <div>
                                                <p>{{ star.intro|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                <span class="glyphicon glyphicon-calendar"></span>
                                                {{ star.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ star.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if star_list.has_previous %}
                            <a href="/star/search/?q={{ query }}&page={{ star_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num star_list.number %}
                            <li class="active">
                                <span class="current">{{ star_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/star/search/?q={{ query }}&page={{ page_num }}"">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if star_list.has_next %}
                            <a href="/star/search/?q={{ query }}&page={{ star_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门明星</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/star/{{ hottest.srcid }}">{{ hottest.name }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}