book/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<book_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^(?P<book_id>[0-9]+)/comment/$', views.comment, name='comment'),
        url(r'^(?P<book_id>[0-9]+)/support/$', views.support, name='support'),
        ]

movie/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<movie_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^(?P<movie_id>[0-9]+)/comment/$', views.comment, name='comment'),
        url(r'^(?P<movie_id>[0-9]+)/support/$', views.support, name='support'),
        ]

pynxl/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pynxl.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('homepage.urls')),
    url(r'^foodmaterial/', include('foodmaterial.urls')),
    url(r'^cookbook/', include('cookbook.urls')),
    url(r'^movie/', include('movie.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^image/', include('image.urls')),
    url(r'^star/', include('star.urls')),
    url(r'^health/', include('health.urls')),
    url(r'^shopping/', include('shopping.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^usercenter/', include('usercenter.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^djadmin/', include('djadmin.urls')),
]

movie/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from datetime import datetime

from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class CrawlerMovieInfo(models.Model):
    id = models.IntegerField('电影编号')
    website = models.CharField('网站来源', max_length=255, blank=True)
    srcid = models.CharField('采集编号', primary_key=True, max_length=255, blank=True)
    srclink = models.CharField('采集URL', max_length=255, blank=True)
    type = models.IntegerField('一级分类', blank=True, null=True)
    extratype = models.IntegerField('二级分类', blank=True, null=True)
    moviename = models.CharField('电影名称', max_length=255, blank=True)
    starring = models.TextField('电影主演', blank=True)
    language = models.CharField('电影语言', max_length=255, blank=True)
    area = models.CharField('地区', max_length=255, blank=True)
    director = models.CharField('导演', max_length=255, blank=True)
    movietype = models.CharField('类型', max_length=255, blank=True)
    writer = models.CharField('编剧', max_length=255, blank=True)
    release_company = models.TextField('发行公司', blank=True)
    release_time = models.DateField('上映时间', blank=True, null=True)
    manufacture_company = models.TextField('制片公司', blank=True)
    alias = models.TextField('别名', blank=True)
    score = models.FloatField('得分')
    story = models.TextField('剧情简介', blank=True)
    viewnum = models.IntegerField('浏览', blank=True)
    supportnum = models.IntegerField('支持', blank=True)
    againstnum = models.IntegerField('反对', blank=True)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_movie_info'
        verbose_name = '电影信息'
        verbose_name_plural = '电影信息'

    def labels_as_list(self):
        return self.movietype.split('/')

    def get_time_string(self):
        return self.createtime.strftime("%Y-%m-%d %H:%M:%S")

    def get_release_time_string(self):
        if self.release_time:
            return self.release_time.strftime("%Y-%m-%d")
        else:
            return ""

class CrawlerMoviePlaylink(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerMovieInfo', db_column='srcid', on_delete=models.CASCADE)
    linkname = models.CharField('电影来源', max_length=255)
    playlink = models.CharField('播放链接', max_length=255)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_movie_playlink'
        verbose_name = '播放链接'
        verbose_name_plural = '播放链接'

class CrawlerMovieImg(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerMovieInfo', db_column='srcid', on_delete=models.CASCADE)
    imgid = models.CharField('图片ID', max_length=255)
    imglink = models.CharField('图片链接', max_length=255)
    imgpath = models.CharField('图片路径', max_length=255)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_movie_img'
        verbose_name = '电影图片'
        verbose_name_plural = '电影图片'

class CrawlerMovieComment(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerMovieInfo', db_column='srcid', on_delete=models.CASCADE)
    comment = models.TextField('评论内容', blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='用户')
    supportnum = models.IntegerField('支持', blank=True)
    createtime = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'crawler_movie_comment'
        verbose_name = '电影评论'
        verbose_name_plural = '电影评论'

movie/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import json
import urllib2

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaulttags import register

from django import template
from django.utils import timezone
from django.views.generic import View, TemplateView, ListView, DetailView

from homepage.models import Website, Column
from .models import CrawlerMovieInfo, CrawlerMoviePlaylink, CrawlerMovieImg, CrawlerMovieComment

@register.filter(name='mod_lookup')
def mod_lookup(num, val):
    return num % val

def index(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=4)

    movie_list = CrawlerMovieInfo.objects.filter(id__lt=29719).order_by('-createtime')[:1000]
    hottest_list = CrawlerMovieInfo.objects.order_by('-score')[:10]

    paginator = Paginator(movie_list, 20)
    try:
        movies = paginator.page(1)
    except EmptyPage:
        movies = paginator.page(paginator.num_pages)

    page_range = list(paginator.page_range)[0:5]

    context = {'site_info': site_info, 
            'column_list': column_list,
            'column_now': column_now,
            'movie_list': movies,
            'query_num': len(movie_list),
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'movie/index.html', context)

def search(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=4)

    movie_list = CrawlerMovieInfo.objects.filter(id__lt=29719)
    query = request.GET.get('q')
    if query and len(query):
        movie_list = movie_list.filter(moviename__contains=query.encode('utf-8'))

    movietype = request.GET.get('type')
    if movietype and len(movietype):
        movie_list = movie_list.filter(movietype__contains=movietype.encode('utf-8'))

    star = request.GET.get('star')
    if star and len(star):
        movie_list = movie_list.filter(starring__contains=star.encode('utf-8'))

    sort = request.GET.get('sort')
    if sort == '1':
    	movie_list = movie_list.order_by('-createtime')[:1000]
    elif sort == '2':
    	movie_list = movie_list.order_by('-viewnum')[:1000]
    elif sort == '3':
    	movie_list = movie_list.order_by('-score')[:1000]
    else:
        sort = '1'
    	movie_list = movie_list.order_by('-createtime')[:1000]

    page = request.GET.get('page', 1)
    paginator = Paginator(movie_list, 20)
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        movies = paginator.page(1)
    except EmptyPage:
        movies = paginator.page(paginator.num_pages)

    page_num = int(page)
    if page_num >= 5:
        page_range = list(paginator.page_range)[page_num-5:page_num+4]
    else:
        page_range = list(paginator.page_range)[0:page_num+4]

    hottest_list = CrawlerMovieInfo.objects.order_by('-viewnum')[:10]

    context = {'site_info': site_info, 
            'column_list': column_list, 
            'column_now': column_now,
            'query': query,
            'sort': int(sort),
            'query_num': len(movie_list),
            'movie_list': movies,
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'movie/search.html', context)

def detail(request, movie_id):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=4)

    movie = get_object_or_404(CrawlerMovieInfo, srcid=str(movie_id))
    movie.viewnum += 1
    movie.save()

    hottest_comment_list = []
    latest_comment_list = movie.crawlermoviecomment_set.order_by('-createtime')
    if len(latest_comment_list) > 30:
        hottest_comment_list = movie.crawlermoviecomment_set.order_by('-supportnum')[:5]

    hottest_list = CrawlerMovieInfo.objects.order_by('-viewnum')[:10]

    context = {'site_info': site_info, 
            'column_list': column_list, 
            'column_now': column_now,
            'movie': movie,
            'hottest_comment_list': hottest_comment_list,
            'latest_comment_list': latest_comment_list,
            'hottest_list': hottest_list,}
    return render(request, 'movie/detail.html', context)

def vote(request, movie_id):
    article_type = request.POST.get("type")

    movie = get_object_or_404(CrawlerMovieInfo, srcid=str(movie_id))

    response = {}
    response['status'] = 0

    if article_type == '1':
        movie.supportnum += 1
        movie.save()

        response['message'] = 'ok'
        response['supportnum'] = movie.supportnum
        response['againstnum'] = movie.againstnum
    elif article_type == '2':
        movie.againstnum += 1
        movie.save()

        response['message'] = 'ok'
        response['supportnum'] = movie.supportnum
        response['againstnum'] = movie.againstnum
    else:
        response['status'] = -1
        response['message'] = 'param type error!'

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

def comment(request, movie_id):
    comment = request.POST.get("comment")
    user = request.user

    if not user.is_authenticated():
        return HttpResponse("亲，你还没有登录哦！", status=403)

    if not comment:
        return HttpResponse("请输入评论内容！", status=403)

    if len(comment.strip())<5:
        return HttpResponse("评论内容内容过短！", status=403)

    movie_comment = CrawlerMovieComment()
    movie_comment.srcid = CrawlerMovieInfo.objects.get(srcid=str(movie_id))
    movie_comment.comment = comment
    movie_comment.user = user
    movie_comment.supportnum = 0
    movie_comment.againstnum = 0
    movie_comment.save()

    context = {'latest': movie_comment,}
    return render(request, "movie/latest_comment.html", context)

def support(request, movie_id):
    cid = request.POST.get("cid")

    comment = get_object_or_404(CrawlerMovieComment, id=cid)

    response = {}
    response['status'] = 0

    comment.supportnum += 1
    comment.save()

    response['message'] = 'ok'
    response['supportnum'] = comment.supportnum

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

movie/templates/movie/index.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation"><a href="/movie/search/?q=&sort=3">评分最高</a></li>
                        <li role="presentation"><a href="/movie/search/?q=&sort=2">热门</a></li>
                        <li role="presentation" class="active"><a href="/movie/search/?q=&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if movie_list %}
                    <ul class="list-group">
                        {% for movie in movie_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="http://119.61.64.177/img001/{{ movie.crawlermovieimg_set.first.imgpath }}" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/movie/{{ movie.srcid }}">
                                                    <strong>{{ movie.moviename|slice:"50" }}</strong>
                                                    <small>{{ movie.get_release_time_string|slice:"4" }}</small>
                                                </a>
                                            </h4>
                                        </div>

                                        <div class="article-labels">
                                            {% for label in movie.labels_as_list %}
                                                <a href="/movie/search/?type={{ label }}"><span class="label label-pynxl-{{ forloop.counter|mod_lookup:6 }}">{{ label }}</span></a>
                                            {% endfor %}
                                        </div>

                                        </br>

                                        <div class="atricle-content">
                                            <div>
                                                <p>{{ movie.story|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                <span class="glyphicon glyphicon-calendar"></span>
                                                {{ movie.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ movie.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if movie_list.has_previous %}
                            <a href="/movie/search/?q={{ query }}&page={{ movie_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num movie_list.number %}
                            <li class="active">
                                <span class="current">{{ movie_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/movie/search/?q={{ query }}&page={{ page_num }}"">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if movie_list.has_next %}
                            <a href="/movie/search/?q={{ query }}&page={{ movie_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门电影</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/movie/{{ hottest.srcid }}">{{ hottest.moviename }}</a>
                                <span class="pull-right" style="color: red">
                                    {{ hottest.score }}
                                </span>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

movie/templates/movie/search.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation" {% ifequal sort 3 %}class="active"{% endifequal %}><a href="/movie/search/?q={{ query }}&sort=3">评分最高</a></li>
                        <li role="presentation" {% ifequal sort 2 %}class="active"{% endifequal %}><a href="/movie/search/?q={{ query }}&sort=2">热门</a></li>
                        <li role="presentation" {% ifequal sort 1 %}class="active"{% endifequal %}><a href="/movie/search/?q={{ query }}&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if movie_list %}
                    <ul class="list-group">
                        {% for movie in movie_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="http://119.61.64.177/img001/{{ movie.crawlermovieimg_set.first.imgpath }}" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/movie/{{ movie.srcid }}">
                                                    <strong>{{ movie.moviename|slice:"50" }}</strong>
                                                    <small>{{ movie.get_release_time_string|slice:"4" }}</small>
                                                </a>
                                            </h4>
                                        </div>

                                        <div class="article-labels">
                                            {% for label in movie.labels_as_list %}
                                                <a href="/movie/search/?type={{ label }}"><span class="label label-pynxl-{{ forloop.counter|mod_lookup:6 }}">{{ label }}</span></a>
                                            {% endfor %}
                                        </div>

                                        </br>

                                        <div class="atricle-content">
                                            <div>
                                                <p>{{ movie.story|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                <span class="glyphicon glyphicon-calendar"></span>
                                                {{ movie.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ movie.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if movie_list.has_previous %}
                            <a href="/movie/search/?q={{ query }}&page={{ movie_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num movie_list.number %}
                            <li class="active">
                                <span class="current">{{ movie_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/movie/search/?q={{ query }}&page={{ page_num }}"">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if movie_list.has_next %}
                            <a href="/movie/search/?q={{ query }}&page={{ movie_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门电影</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/movie/{{ hottest.srcid }}">{{ hottest.moviename }}</a>
                                <span class="pull-right" style="color: red">
                                    {{ hottest.score }}
                                </span>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}