book/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^search/$', views.search, name='search'),
        url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<book_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^(?P<book_id>[0-9]+)/comment/$', views.comment, name='comment'),
        url(r'^(?P<book_id>[0-9]+)/support/$', views.support, name='support'),
        ]

pynxl/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pynxl.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('homepage.urls')),
    url(r'^foodmaterial/', include('foodmaterial.urls')),
    url(r'^cookbook/', include('cookbook.urls')),
    url(r'^movie/', include('movie.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^image/', include('image.urls')),
    url(r'^star/', include('star.urls')),
    url(r'^health/', include('health.urls')),
    url(r'^shopping/', include('shopping.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^usercenter/', include('usercenter.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^djadmin/', include('djadmin.urls')),
]

book/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from datetime import datetime

from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class CrawlerBookInfo(models.Model):
    id = models.IntegerField('图书编号')
    website = models.CharField('网站来源', max_length=255, blank=True)
    srcid = models.CharField('采集编号', primary_key=True, max_length=255, blank=True)
    srclink = models.CharField('采集URL', max_length=255, blank=True)
    type = models.IntegerField('一级分类', blank=True, null=True)
    extratype = models.IntegerField('二级分类', blank=True, null=True)
    bookname = models.CharField('图书名称', max_length=255, blank=True)
    subtitle = models.CharField('副标题', max_length=255, blank=True)
    originname = models.CharField('原作名', max_length=255, blank=True)
    author = models.CharField('作者', max_length=255, blank=True)
    translator = models.CharField('译者', max_length=255, blank=True)
    press = models.CharField('出版社', max_length=255, blank=True)
    year = models.DateField('出版年', max_length=255, blank=True)
    page = models.CharField('页数', max_length=255, blank=True)
    price = models.CharField('定价', max_length=255, blank=True)
    collection = models.CharField('丛书', max_length=255, blank=True)
    bidding = models.CharField('装帧', max_length=255, blank=True)
    isbn = models.CharField('ISBN', max_length=255, blank=True)
    score = models.FloatField('得分')
    content_intro = models.TextField('内容简介', blank=True)
    author_intro = models.TextField('作者简介', blank=True)
    dir = models.TextField('目录', blank=True)
    reviewlink = models.CharField('评论链接', max_length=255, blank=True)
    viewnum = models.IntegerField('浏览', blank=True)
    supportnum = models.IntegerField('支持', blank=True)
    againstnum = models.IntegerField('反对', blank=True)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_book_info'
        verbose_name = '图书信息'
        verbose_name_plural = '图书信息'

    def get_time_string(self):
        return self.createtime.strftime("%Y-%m-%d %H:%M:%S")

    def get_year_string(self):
        return self.year.strftime("%Y-%m-%d")

class CrawlerBookBuy(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerBookInfo', db_column='srcid', on_delete=models.CASCADE)
    link = models.CharField('链接', max_length=255)
    sitename = models.CharField('站点', max_length=255)
    dyprice = models.CharField('价格', max_length=255)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_book_buy'
        verbose_name = '购买链接'
        verbose_name_plural = '购买链接'

class CrawlerBookImg(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerBookInfo', db_column='srcid', on_delete=models.CASCADE)
    imgid = models.CharField('图片ID', max_length=255)
    imglink = models.CharField('图片链接', max_length=255)
    imgpath = models.CharField('图片路径', max_length=255)
    createtime = models.DateTimeField('创建时间', blank=True, null=True)
    updatetime = models.DateTimeField('更新时间', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'crawler_book_img'
        verbose_name = '电影图片'
        verbose_name_plural = '电影图片'

class CrawlerBookComment(models.Model):
    id = models.IntegerField(primary_key=True)
    srcid = models.ForeignKey('CrawlerBookInfo', db_column='srcid', on_delete=models.CASCADE)
    comment = models.TextField('评论内容', blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='用户')
    supportnum = models.IntegerField('支持', blank=True)
    createtime = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'crawler_book_comment'
        verbose_name = '电影评论'
        verbose_name_plural = '电影评论'

book/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import json
import urllib2

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaulttags import register

from django import template
from django.utils import timezone
from django.views.generic import View, TemplateView, ListView, DetailView

from homepage.models import Website, Column
from .models import CrawlerBookInfo, CrawlerBookBuy, CrawlerBookImg, CrawlerBookComment

@register.filter(name='mod_lookup')
def mod_lookup(num, val):
    return num % val

def index(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=5)

    book_list = CrawlerBookInfo.objects.order_by('-createtime')[:1000]
    hottest_list = CrawlerBookInfo.objects.order_by('-supportnum')[:10]

    paginator = Paginator(book_list, 20)
    try:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    page_range = list(paginator.page_range)[0:5]

    context = {'site_info': site_info, 
            'column_list': column_list,
            'column_now': column_now,
            'book_list': books,
            'query_num': len(book_list),
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'book/index.html', context)

def search(request):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=5)

    book_list = CrawlerBookInfo.objects.all()
    query = request.GET.get('q')
    if query and len(query):
        book_list = book_list.filter(bookname__contains=query.encode('utf-8'))

    sort = request.GET.get('sort')
    if sort == '1':
    	book_list = book_list.order_by('-createtime')[:1000]
    elif sort == '2':
    	book_list = book_list.order_by('-viewnum')[:1000]
    elif sort == '3':
    	book_list = book_list.order_by('-supportnum')[:1000]
    else:
        sort = '1'
    	book_list = book_list.order_by('-createtime')[:1000]

    page = request.GET.get('page', 1)
    paginator = Paginator(book_list, 20)
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    page_num = int(page)
    if page_num >= 5:
        page_range = list(paginator.page_range)[page_num-5:page_num+4]
    else:
        page_range = list(paginator.page_range)[0:page_num+4]

    hottest_list = CrawlerBookInfo.objects.order_by('-supportnum')[:10]

    context = {'site_info': site_info,
            'column_list': column_list,
            'column_now': column_now,
            'query': query,
            'sort': int(sort),
            'query_num': len(book_list),
            'book_list': books,
            'page_range': page_range,
            'hottest_list': hottest_list,}
    return render(request, 'book/search.html', context)

def detail(request, book_id):
    site_info = Website.objects.first()
    column_list = Column.objects.order_by('column_order')
    column_now = Column.objects.get(pk=5)

    book = get_object_or_404(CrawlerBookInfo, srcid=str(book_id))
    book.viewnum += 1
    book.save()

    hottest_comment_list = []
    latest_comment_list = book.crawlerbookcomment_set.order_by('-createtime')
    if len(latest_comment_list) > 30:
        hottest_comment_list = book.crawlerbookcomment_set.order_by('-supportnum')[:5]

    hottest_list = CrawlerBookInfo.objects.order_by('-supportnum')[:10]

    context = {'site_info': site_info, 
            'column_list': column_list, 
            'column_now': column_now,
            'book': book,
            'hottest_comment_list': hottest_comment_list,
            'latest_comment_list': latest_comment_list,
            'hottest_list': hottest_list,}
    return render(request, 'book/detail.html', context)

def vote(request, book_id):
    article_type = request.POST.get("type")

    book = get_object_or_404(CrawlerBookInfo, srcid=str(book_id))

    response = {}
    response['status'] = 0

    if article_type == '1':
        book.supportnum += 1
        book.save()

        response['message'] = 'ok'
        response['supportnum'] = book.supportnum
        response['againstnum'] = book.againstnum
    elif article_type == '2':
        book.againstnum += 1
        book.save()

        response['message'] = 'ok'
        response['supportnum'] = book.supportnum
        response['againstnum'] = book.againstnum
    else:
        response['status'] = -1
        response['message'] = 'param type error!'

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

def comment(request, book_id):
    comment = request.POST.get("comment")
    user = request.user

    if not user.is_authenticated():
        return HttpResponse("亲，你还没有登录哦！", status=403)

    if not comment:
        return HttpResponse("请输入评论内容！", status=403)

    if len(comment.strip())<5:
        return HttpResponse("评论内容内容过短！", status=403)

    book_comment = CrawlerBookComment()
    book_comment.srcid = CrawlerBookInfo.objects.get(srcid=str(book_id))
    book_comment.comment = comment
    book_comment.user = user
    book_comment.supportnum = 0
    book_comment.againstnum = 0
    book_comment.save()

    context = {'latest': book_comment,}
    return render(request, "book/latest_comment.html", context)

def support(request, book_id):
    cid = request.POST.get("cid")

    comment = get_object_or_404(CrawlerBookComment, id=cid)

    response = {}
    response['status'] = 0

    comment.supportnum += 1
    comment.save()

    response['message'] = 'ok'
    response['supportnum'] = comment.supportnum

    return HttpResponse (
        json.dumps(response),
        content_type="application/json"
    )

book/templates/book/index.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation"><a href="/book/search/?q=&sort=3">推荐</a></li>
                        <li role="presentation"><a href="/book/search/?q=&sort=2">热门</a></li>
                        <li role="presentation" class="active"><a href="/book/search/?q=&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if book_list %}
                    <ul class="list-group">
                        {% for book in book_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="http://119.61.64.177/img001/{{ book.crawlerbookimg_set.first.imgpath }}" style="height: 200px; width: 132px" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/book/{{ book.srcid }}">
                                                    <strong>{{ book.bookname|slice:"50" }}</strong>
                                                    <small>{{ book.subtitle }}</small>
                                                </a>
                                            </h4>
                                        </div>

                                        </br>

                                        <div class="article-content">
                                            <div>
                                                <p>{{ book.content_intro|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                <span class="glyphicon glyphicon-calendar"></span>
                                                {{ book.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ book.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if book_list.has_previous %}
                            <a href="/book/search/?q={{ query }}&page={{ book_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num book_list.number %}
                            <li class="active">
                                <span class="current">{{ book_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/book/search/?q={{ query }}&page={{ page_num }}"">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if book_list.has_next %}
                            <a href="/book/search/?q={{ query }}&page={{ book_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门图书</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/book/{{ hottest.srcid }}">{{ hottest.bookname }}</a>
                                <span class="pull-right" style="color: red">
                                    {{ hottest.score }}
                                </span>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

book/templates/book/search.html
{% extends "homepage/base.html" %}

{% block title %}<title>{{ column_now.column_name }}_{{ site_info.site_name }}_{{ site_info.site_slogan }}</title>{% endblock %}
{% block keywords %}<meta name="keywords" content="{{ site_info.site_keywords }}"/>{% endblock %}
{% block description %}<meta name="description" content="{{ site_info.site_description }}"/>{% endblock %}

{%block main%}

<div class="container">
    <div class="row">
        <div class="col-md-8 column">
            <div class="article-list panel panel-pynxl">
                <div class="panel-heading">
                    <ul class="nav nav-tabs nav-tabs-pynxl">
                        <li role="presentation">
                            <h4>
                                <span class="{{ column_now.column_icon }}"></span>
                                &nbsp;
                                {{ column_now.column_name }}
                            </h4>
                        </li>
                        <li role="presentation" {% ifequal sort 3 %}class="active"{% endifequal %}><a href="/book/search/?q={{ query }}&sort=3">推荐</a></li>
                        <li role="presentation" {% ifequal sort 2 %}class="active"{% endifequal %}><a href="/book/search/?q={{ query }}&sort=2">热门</a></li>
                        <li role="presentation" {% ifequal sort 1 %}class="active"{% endifequal %}><a href="/book/search/?q={{ query }}&sort=1">最新</a></li>
                    </ul>
                </div>

                {% if book_list %}
                    <ul class="list-group">
                        {% for book in book_list %}
                            <li class="article list-group-item">
                                <div class="row">
                                    <div class="col-xs-4 col-md-3">
                                        <div class="artitle-img">
                                            <img src="http://119.61.64.177/img001/{{ book.crawlerbookimg_set.first.imgpath }}" style="height: 200px; width: 132px" class="img-rounded img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-8 col-md-9">
                                        <div class="article-title clearfix">
                                            <h4>
                                                <a href="/book/{{ book.srcid }}">
                                                    <strong>{{ book.bookname|slice:"50" }}</strong>
                                                    <small>{{ book.get_release_time_string|slice:"4" }}</small>
                                                </a>
                                            </h4>
                                        </div>

                                        </br>

                                        <div class="atricle-content">
                                            <div>
                                                <p>{{ book.story|slice:"125" }}...</p>
                                            </div>
                                        </div>

                                        <div class="article-info text-right">
                                            <span>
                                                <span class="glyphicon glyphicon-calendar"></span>
                                                {{ book.get_time_string }}
                                            </span>
                                            <span>
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                                {{ book.viewnum }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>没有查询到任何信息。</p>
                {% endif %}
            </div>

            <div class="text-center">
                <ul class="pagination">
                    <li>
                        {% if book_list.has_previous %}
                            <a href="/book/search/?q={{ query }}&page={{ book_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>

                    {% for page_num in page_range %}
                        {% ifequal page_num book_list.number %}
                            <li class="active">
                                <span class="current">{{ book_list.number }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="/book/search/?q={{ query }}&page={{ page_num }}"">
                                    <span>{{ page_num }}</span>
                                </a>
                            </li>
                        {% endifequal %}
                    {% endfor %}  

                    <li>
                        {% if book_list.has_next %}
                            <a href="/book/search/?q={{ query }}&page={{ book_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li><span>查询到{{ query_num }}条记录</span></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4 column">
            <div class="panel panel-pynxl">
                <div class="panel-heading">
                    <h5>
                        <span class="glyphicon glyphicon-flag"></span>
                        <strong>热门图书</strong>
                    </h5>
                </div>
                <ul class="list-group" id="hottest-you-like">
                    {% if hottest_list %}
                        {% for hottest in hottest_list %}
                            <li class="list-group-item">
                                <span class="badge pull-left">
                                    {{ hottest.viewnum }}
                                </span>
                                &nbsp;
                                <a href="/book/{{ hottest.srcid }}">{{ hottest.bookname }}</a>
                                <span class="pull-right" style="color: red">
                                    {{ hottest.score }}
                                </span>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}